### ISSUE TITLE
Problem importing pieceofcake.version when using development version

### ISSUE THREAD

**Issue by namurphy** [astrofrog/pieceofcake#2]
I ran into a problem when doing a local pip install of pieceofcake of a clone of the GitHub repository, which I mentioned in #1.  I tried:
```bash
cd /location/of/pieceofcake_repo
pip install .
```
That command seemed to work, but I ran into a problem when I ran:
```pycon
>>> import pieceofcacke
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/namurphy/Projects/pieceofcake/pieceofcake/__init__.py", line 1, in <module>
    from .version import version as __version__
ModuleNotFoundError: No module named 'pieceofcake.version'
```
I did not get this problem when trying to import version 0.1 which I installed from `pip install pieceofcake`.

This could perhaps be resolved by doing a `try`/`except` on the import statement, and otherwise setting a default for the version number that indicates it's a development version.

**Comment by astrofrog** [comment]
Oops yes the issue was a missing ``pyproject.toml`` file, I've added it in https://github.com/astrofrog/pieceofcake/commit/74d22cdc91bd87549336394d6ccf98638e55f1c6. Can you try again?

**Comment by namurphy** [comment]
> Oops yes the issue was a missing `pyproject.toml` file, I've added it in [74d22cd](https://github.com/astrofrog/pieceofcake/commit/74d22cdc91bd87549336394d6ccf98638e55f1c6). Can you try again?

Yep, that worked.  Thank you!
